"""Phase 6 §43 OpenCode plugin package.

Generates a deterministic OpenCode plugin package from one
release input set:

* ``package.json`` — npm-publishable manifest.
* ``plugin/project-intelligence.ts`` — OpenCode plugin entry.
* ``skill/project-intelligence/SKILL.md`` — canonical skill
  (byte-equal to the canonical package).
* ``config/opencode.example.jsonc`` — example MCP configuration.
* ``README.md`` — vendor-facing installation instructions.

The package is publishable as a versioned npm package or
usable as a local project plugin (the contract supports
both). When the active OpenCode version supports Agent Skills
loading, the plugin embeds the canonical skill; otherwise it
falls back to the minimal bootstrap instructions.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

from pi_platform.core.agent_integration.supply_chain_gate import (
    PluginSupplyChainSecurityGate,
    SupplyChainVerdict,
)


__all__ = [
    "OpenCodePluginPackageError",
    "OpenCodePluginPackager",
]


log = logging.getLogger(__name__)


class OpenCodePluginPackageError(RuntimeError):
    """Raised when the OpenCode bundle cannot be generated."""


_OPENCODE_PLUGIN_ENTRY = """\
// Auto-generated by Project Intelligence Platform.
//
// Minimal OpenCode plugin entry point. The actual retrieval /
// business logic remains in the Project Intelligence core; this
// entry only configures the MCP endpoint and bootstraps the
// canonical Agent Skill.

import type { Plugin } from "@opencode-ai/plugin";

export const ProjectIntelligencePlugin: Plugin = async ({ client }) => {
  await client.app.mcp.register({
    name: "project-intelligence",
    endpoint: process.env.PI_MCP_ENDPOINT || "stdio://",
    apiVersion: process.env.PI_MCP_API_VERSION || ">=1.3.0 <2.0.0",
  });
  return {};
};
"""


def _opencode_manifest(release, bundle_path: str) -> dict:
    return {
        "name": "project-intelligence-plugin",
        "version": release.skill_version,
        "description": "OpenCode plugin for the Project Intelligence Platform.",
        "license": release.license,
        "author": "project-intelligence",
        "type": "module",
        "main": "plugin/project-intelligence.js",
        "exports": {
            ".": "./plugin/project-intelligence.js",
        },
        "scripts": {
            "build": "tsc plugin/project-intelligence.ts",
        },
        "opencode": {
            "skills": {
                "name": "project-intelligence",
                "version": release.skill_version,
                "sha256": release.skill_sha256,
            },
            "mcp": {
                "endpoint": release.mcp_endpoint,
                "apiVersion": release.mcp_api_range,
            },
            "distribution": {
                "schemaVersion": 1,
                "manifestUri": "project-intelligence://distribution/manifest",
            },
            "okf": {
                "supported": list(release.okf_profile_versions),
            },
        },
        "repository": {
            "type": "git",
            "url": release.source_repository,
        },
        "bundlePath": bundle_path,
    }


def _opencode_example_config(release) -> dict:
    return {
        "$schema": "https://opencode.dev/schema.json",
        "mcp": {
            "project-intelligence": {
                "endpoint": release.mcp_endpoint,
                "apiVersion": release.mcp_api_range,
                "transport": "stdio",
            },
        },
        "skill": {
            "name": "project-intelligence",
            "version": release.skill_version,
            "sha256": release.skill_sha256,
        },
    }


def _walk_files(skill_dir: Path) -> list[Path]:
    if not skill_dir.is_dir():
        return []
    out: list[Path] = []
    for p in sorted(skill_dir.rglob("*")):
        if p.is_file() and not p.is_symlink():
            out.append(p)
    return out


class OpenCodePluginPackager:
    """§43 OpenCode plugin packager."""

    def __init__(self, *,
                 skills_root: Path,
                 gate: PluginSupplyChainSecurityGate,
                 bootstrap_fallback: bool = False):
        self._skills_root = Path(skills_root)
        self._gate = gate
        self._bootstrap_fallback = bootstrap_fallback

    @property
    def vendor(self) -> str:
        return "opencode"

    def package(self, release, *,
                output_root: Path) -> SupplyChainVerdict:
        from pi_platform.adapters.agent_integration.packagers.codex import (
            ReleaseInputSet,
        )
        assert isinstance(release, ReleaseInputSet)
        skill_name = "project-intelligence"
        skill_dir = self._skills_root / skill_name
        if not skill_dir.is_dir():
            raise OpenCodePluginPackageError(
                f"skill package not found: {skill_dir}"
            )
        bundle_root = Path(output_root) / self.vendor
        bundle_root.mkdir(parents=True, exist_ok=True)

        # OpenCode bundle layout.
        plugin_dir = bundle_root / "plugin"
        plugin_dir.mkdir(parents=True, exist_ok=True)
        (plugin_dir / "project-intelligence.ts").write_bytes(
            _OPENCODE_PLUGIN_ENTRY.encode("utf-8"))
        (plugin_dir / "project-intelligence.js").write_bytes(
            b"// generated; see project-intelligence.ts\n")

        skill_dest = bundle_root / "skill" / skill_name
        skill_dest.mkdir(parents=True, exist_ok=True)
        if not self._bootstrap_fallback:
            for src in _walk_files(skill_dir):
                rel = src.relative_to(skill_dir)
                tgt = skill_dest / rel
                tgt.parent.mkdir(parents=True, exist_ok=True)
                tgt.write_bytes(src.read_bytes())
        else:
            (skill_dest / "README.md").write_bytes(
                b"# Project Intelligence\n\n"
                b"This OpenCode client does not support Agent Skills "
                b"loading; use the MCP server directly via "
                b"`project-intelligence://distribution/manifest`.\n"
            )

        config_dir = bundle_root / "config"
        config_dir.mkdir(parents=True, exist_ok=True)
        example = _opencode_example_config(release)
        (config_dir / "opencode.example.jsonc").write_bytes(
            json.dumps(example, sort_keys=True,
                       separators=(",", ":")).encode("utf-8"))

        # ``package.json``.
        manifest = _opencode_manifest(release,
                                    str(bundle_root.relative_to(output_root)))
        (bundle_root / "package.json").write_bytes(
            json.dumps(manifest, sort_keys=True,
                       separators=(",", ":")).encode("utf-8"))

        # ``README.md``.
        readme = (
            "# Project Intelligence (OpenCode plugin)\n\n"
            "Install locally with:\n\n"
            "```\nopencode plugin install ./project-intelligence-plugin\n"
            "```\n\n"
            "Or publish to npm and configure in your "
            "`opencode.json`.\n"
        )
        (bundle_root / "README.md").write_bytes(readme.encode("utf-8"))

        bundle_manifest = {
            "skillVersion": release.skill_version,
            "skillSha256": release.skill_sha256,
            "canonicalSkillSha256": release.skill_sha256,
            "mcpApiRange": release.mcp_api_range,
            "license": release.license,
            "serverIdentity": {
                "skillSha256": release.skill_sha256,
                "serverVersion": release.server_version,
                "mcpApiRange": release.mcp_api_range,
                "license": release.license,
            },
            "sourceRepository": release.source_repository,
            "permissions": dict(release.permissions or {}),
            "networkRequirements": dict(release.network_requirements or {}),
            "scripts": {},
        }
        verdict = self._gate.run(str(bundle_root.relative_to(output_root)), bundle_manifest)
        provenance_path = bundle_root / "PROVENANCE.json"
        provenance = {"bundlePath": str(bundle_root.relative_to(output_root))}
        provenance_out = self._gate.record_in_provenance(
            verdict, provenance,
        )
        provenance_path.write_bytes(json.dumps(
            provenance_out, sort_keys=True,
            separators=(",", ":")).encode("utf-8"))
        return verdict

    @staticmethod
    def bundle_inventory(bundle_root: Path) -> dict[str, str]:
        from hashlib import sha256
        out: dict[str, str] = {}
        for p in sorted(bundle_root.rglob("*")):
            if p.is_file() and not p.is_symlink():
                rel = str(p.relative_to(bundle_root))
                out[rel] = sha256(p.read_bytes()).hexdigest()
        return out